name: Checkstyle

on: [workflow_dispatch, pull_request]

jobs:
  checkstyle_job:
    runs-on: ubuntu-latest
    name: Checkstyle job
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Run check style
        uses: nikitasavinov/checkstyle-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          reporter: 'github-pr-check'
          tool_name: 'Validate codestyle'
          checkstyle_config: 'checkstyle.xml'
          level: 'error'
          fail_on_error: 'true'
          properties_file: 'checkstyle.xml'
